---
- name: "Facts: Run zpool_facts"
  community.general.zpool_facts:

- name: "Facts: Debug ansible_zfs_pools"
  ansible.builtin.debug:
    var: ansible_zfs_pools
  when: fzfs_debug | bool

- name: "Facts: Debug list pools"
  ansible.builtin.debug:
    msg: name [{{ item.name }}], size [{{ item.size }}], free [{{ item.free }}]
  loop: "{{ ansible_zfs_pools }}"
  loop_control:
    label: "{{ item.name }}"
  when: fzfs_debug | bool

- name: "Facts: Run zfs_facts"
  community.general.zfs_facts:
    name: "{{ item.name }}"
    recurse: "{{ fzfs_facts_recurse }}"
  loop: "{{ ansible_zfs_pools }}"
  loop_control:
    label: "{{ item.name }}"
  register: ansible_zfs_ds

- name: "Facts: Debug ansible_zfs_ds"
  ansible.builtin.debug:
    var: ansible_zfs_ds
  when: fzfs_debug | bool

- name: "Facts: Get list of datasets"
  ansible.builtin.include_tasks: facts_include_1.yml
  loop: "{{ ansible_zfs_ds.results }}"
  loop_control:
    label: "{{ item.ansible_facts.ansible_zfs_datasets | map(attribute='name') }}"

- name: "Facts: Debug list of datasets"
  ansible.builtin.debug:
    var: fzfs_datasets
  when: fzfs_debug | bool

# EOF
