---
- name: "Facts:facts_include_1: Create list of datasets"
  ansible.builtin.set_fact:
    fzfs_datasets: >
      {{ fzfs_datasets + [{'pool': item.name,
                           'name': data_set.name,
                           'mountpoint': data_set.mountpoint | d('NONE')}] }}
  loop: "{{ item.ansible_facts.ansible_zfs_datasets }}"
  loop_control:
    loop_var: data_set
    label: "{{ data_set.name }}"

# EOF
