---
# tasks for freebsd_zfs

- name: Include role vbotka.freebsd_postinstall task sysctl
  tags: fzfs_sysctl

  block:
    - name: Set kernel state fzfs_sysctl
      ansible.builtin.set_fact:
        fp_sysctl_conf: "{{ fzfs_sysctl_conf }}"

    - name: Include vbotka.freebsd_postinstall sysctl
      ansible.builtin.include_role:
        name: vbotka.freebsd_postinstall
        tasks_from: sysctl.yml

- name: Include role vbotka.freebsd_postinstall task loader
  tags: fzfs_loader

  block:
    - name: Configure fzfs_sysctl in /boot/loader.conf
      ansible.builtin.set_fact:
        fp_sysctl_conf: "{{ fzfs_sysctl_conf }}"
    - name: Include vbotka.freebsd_postinstall loader
      ansible.builtin.include_role:
        name: vbotka.freebsd_postinstall
        tasks_from: loader.yml
- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: fzfs_debug|bool
  tags: fzfs_debug

- name: Import rcconf.yml
  ansible.builtin.import_tasks: rcconf.yml
  tags: fzfs_rcconf

- name: Import facts.yml
  ansible.builtin.import_tasks: facts.yml
  tags: fzfs_facts

- name: Import manage.yml
  ansible.builtin.import_tasks: manage.yml
  tags: fzfs_manage

# EOF
