---

- name: "Sysctl: Include vbotka.freebsd_postinstall sysctl"
  ansible.builtin.include_role:
    name: vbotka.freebsd_postinstall
    tasks_from: sysctl.yml
    apply:
      tags: fzfs_sysctl
      vars:
        fp_sysctl_conf: "{{ fzfs_sysctl_conf }}"
        fp_sysctl_tuneables_warning: true

# EOF
